### ISSUE TITLE
Compiler error while compiling fsck_ext2fs on FreeBSD

### ISSUE THREAD

**Issue by vpcd** [rumpkernel/rumpctrl#20]
I just learned about the rump kernels and wanted to experiment a bit. I am using FreeBSD 10.2 and the build process fails while compiling fsck_ext2fs:

```
$ ./builnb.sh
... snip ...
( cd src-netbsd/sbin/fsck_ext2fs && /home/viktor/src/rumpctrl/rumptools/rumpmake obj && /home/viktor/src/rumpctrl/rumptools/rumpmake LDFLAGS=-Wl,-r LIBCRT0= BUILDRUMP_CFLAGS="-fPIC -std=gnu99 -D__NetBSD__ " fsck_ext2fs.ro )
#    objdir  /usr/home/viktor/src/rumpctrl/rumpobj/sbin/fsck_ext2fs
#   compile  fsck_ext2fs/dir.o
/usr/home/viktor/src/rumpctrl/rumptools/bin/x86_64--netbsd-clang -O2 -g -fPIC -std=gnu99 -D__NetBSD__    -std=gnu99    -Werror -Wno-error=tautological-pointer-compare   -D__NetBSD__ -U__FreeBSD__ --sysroot=/usr/home/viktor/src/rumpctrl/rumptools/dest  -I/usr/home/viktor/src/rumpctrl/src-netbsd/sbin/fsck  -c    /usr/home/viktor/src/rumpctrl/src-netbsd/sbin/fsck_ext2fs/dir.c
error: unknown warning option '-Werror=tautological-pointer-compare'; did you
      mean '-Werror=tautological-compare'? [-Werror,-Wunknown-warning-option]

*** Failed target:  dir.o
*** Failed command: /usr/home/viktor/src/rumpctrl/rumptools/bin/x86_64--netbsd-clang -O2 -g -fPIC -std=gnu99 -D__NetBSD__ -std=gnu99 -Werror -Wno-error=tautological-pointer-compare -D__NetBSD__ -U__FreeBSD__ --sysroot=/usr/home/viktor/src/rumpctrl/rumptools/dest -I/usr/home/viktor/src/rumpctrl/src-netbsd/sbin/fsck -c /usr/home/viktor/src/rumpctrl/src-netbsd/sbin/fsck_ext2fs/dir.c
*** Error code 1

Stop.
nbmake[1]: stopped in /usr/home/viktor/src/rumpctrl/src-netbsd/sbin/fsck_ext2fs
Makefile:133: recipe for target 'rumpobj/sbin/fsck_ext2fs/fsck_ext2fs.ro' failed
gmake: *** [rumpobj/sbin/fsck_ext2fs/fsck_ext2fs.ro] Error 1
```

Following the compiler's advice and changing the ```tautological-pointer-compare``` option to ```tautological-compare``` in the ```src-netbsd/sbin/fsck_ext2fs/Makefile``` line:

```CWARNFLAGS.clang+= -Wno-error=tautological-pointer-compare``` 

fixes the issue and the build completes successfully.

**Comment by anttikantee** [comment]
The "upstreamable" way to deal with compilers which don't support the flags used in `src-netbsd` is to add the flags to `CCWRAPPER_MANGLE` in buildrump.sh.

**Comment by anttikantee** [comment]
Just to clarify, the implicit question was: "do you want to attempt that patch?"

**Comment by vpcd** [comment]
I am just a novice and not really experienced with build systems, esp. quite complex ones, so don't hold your breath. But I'd like to learn and will give it a try tomorrow after studying buildrump.sh more carefully. Feel free to fix it in the meantime if you doubt in my ability, which you should...

**Comment by anttikantee** [comment]
Consider it your golden opportunity to get feedback on working on a non-trivial system, then ;-)

**Comment by vpcd** [comment]
I have been working on fixing this issue, however, in the process I discovered a limitation
in the internals of the buildrump.sh which prevents mangling of arguments
containing the equals sign, as is the case with the ```-Wno-error=tautological-pointer-compare```. 

I have modified the buildrump.sh script to handle such situations. You can check my work here: https://github.com/vpcd/buildrump.sh/commit/3f9a6dc08bdec9528858f88e390ea782c14d45f5
If this change is accepted, then fixing this issue entails just adding the lenghty 
appendvar_fs incantation to somewhere appropriate.

Note that this is my first try at contributing to somebody else's project on Github so I
didn't do a pull request in case I foresaw doing something important.

**Comment by anttikantee** [comment]
Isn't it possible to always use ' ' instead of '=' as the from/to separator in CCWRAPPER_MANGLE?

**Comment by vpcd** [comment]
It sure is! https://github.com/vpcd/buildrump.sh/commit/198acead25bb9d9295d09e273d9c422c867e9c5d

**Comment by anttikantee** [comment]
Nice. Slightly less readable than the original, but on the plus side it actually works ;-)

Please submit a pull req to buildrump.sh, and another one for the actual mangling.  Don't forget to add yourself to AUTHORS.  Thanks!

**Comment by anttikantee** [comment]
[replying here because submitter left irc]: yes i think you buildrump.sh patch is good.  please open a pull req.  thanks.
(and don't forget AUTHORS!)
