### ISSUE TITLE
VincentS

### ISSUE THREAD

**Issue by VincentS** [rumpkernel/rumpctrl#21]
Hey,

I tried to increase the number of available File Descriptors in Rumprun with sysctl without 
success. It seems that I have to use `ulimit` for increasing them. Is this tool useable in Rumprun / can be pulled from the NetBSD source?

**Comment by anttikantee** [comment]
I don't think ulimit is a command at all, it's a shell builtin.  For example csh users need to use limit, not ulimit.

As discussed on the mailing list, you can use sysctl to adjust those limits, so can this issue be closed?

**Comment by VincentS** [comment]
Sure closed and thanks ! :+1:
